# Workflow found here https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main
      - name: Extract release notes
        run: |
          git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > Release-Notes.txt
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
      #- name: Test
      #  run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push
        run: dotnet nuget push FishbowlSQL.${VERSION}.nupkg --api-key ${NUGETAPIKEY}
        env:
          NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}